language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'
  - nightly

before_script:
  - composer install
  - pear install PHP_CodeSniffer
  - phpenv rehash
  - ls vendor

script:
  - phpcs -n --extensions=php --standard=PSR2 src
  - phpunit --bootstrap vendor/autoload.php tests

# notifications:
#   email:
#     - developer@blitzr.com