language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

before_script:
  - composer install
  - pear install PHP_CodeSniffer
  - phpenv rehash

script:
  - phpcs --extensions=php --standard=PSR2 src

# notifications:
#   email:
#     - developer@blitzr.com